import {CloudAuth} from '../auth/supabase-rest.js';
import {CLOUD_URL,CLOUD_KEY} from '../auth/config.js';
import {BrowserSpeechAdapter} from '../speech-adapter/browser.js';
import {NODES} from '../core/rules.js';
import {renderAdminReport} from './admin-report.js';
const auth=new CloudAuth(CLOUD_URL,CLOUD_KEY),speech=new BrowserSpeechAdapter(),root=document.querySelector('#app');
let profile=null,sessions=[],session=null,busy=false,error='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(content){root.innerHTML=`<header><div class="bar"><div class="brand">TP927 <span class="version">V1.0 · Cloud Test</span></div><div class="row">${profile?`<small>${esc(profile.display_name)} · LV${profile.level}</small><button class="secondary" id="logout">登出</button>`:''}</div></div></header><main>${error?`<div class="notice">${esc(error)}</div>`:''}${content}</main>`;const out=document.querySelector('#logout');if(out)out.onclick=async()=>{await auth.signOut();profile=null;session=null;sessions=[];render()}}
function render(){if(!profile)return login();if(session)return training();return dashboard()}
function login(){shell(`<h1>927 招募教練</h1><div class="card"><h2>管理者建立的帳號登入</h2><form id="login"><p><input type="email" name="email" required placeholder="電子郵件" autocomplete="username"></p><p><input type="password" name="password" required placeholder="密碼" autocomplete="current-password"></p><button class="primary">登入</button></form><p class="muted">V1 不開放自行註冊。帳號由管理者建立。</p></div><a href="./bootstrap.html">首次啟用管理者</a>`);document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await auth.signIn(f.get('email'),f.get('password'));await refresh();error='';render()}catch(x){error=x.message;render()}}}
async function refresh(){const data=await auth.invoke('history');profile=data.profile;sessions=data.sessions}
function dashboard(){const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'}),count=sessions.filter(s=>s.local_date===today).length;
 shell(`<h1>你好，${esc(profile.display_name)}</h1><div class="grid"><div class="card"><h3>目前等級</h3><div class="stat">LV${profile.level}</div></div><div class="card"><h3>今日訓練</h3><div class="stat">${count} / 3</div></div><div class="card"><h3>待複核</h3><div class="stat">${sessions.filter(s=>s.status==='review_required').length}</div></div></div><div class="card"><h2>開始今日訓練</h2><p>人物由系統抽取；每日最多三場。對話與驗證事件同步到專用雲端專案。</p><button class="primary" id="start" ${count>=3?'disabled':''}>開始面談</button></div><div class="card"><h2>訓練紀錄</h2>${sessions.length?sessions.map(s=>`<div class="item">${esc(s.local_date)}　${esc(s.character_name)}　LV${s.level}　<span class="pill">${esc(s.status)}</span>${s.status==='completed'?`　${s.score} 分 · ${s.pass?'PASS':'FAIL'}`:''}</div>`).join(''):'尚無紀錄。'}</div>${profile.is_admin?`<div class="card"><h2>管理者</h2><button class="secondary" id="summary">單位總覽</button><details><summary>建立初始帳號</summary><form id="create"><p><select name="name">${['江建廷','林宜慶','陳嘉瑋','顏伯存','劉孟凱'].map(x=>`<option>${x}</option>`).join('')}</select></p><p><input name="email" type="email" placeholder="成員電子郵件" required></p><p><input name="password" type="password" placeholder="臨時密碼，至少 12 字元" minlength="12" required></p><button class="primary">建立</button></form></details><div id="admin-report"></div></div>`:''}`);
 document.querySelector('#start').onclick=async()=>{try{const r=await auth.invoke('start');session=r.session;error='';render()}catch(x){error=x.message;render()}};
 if(profile.is_admin){document.querySelector('#summary').onclick=async()=>{try{const data=await auth.invoke('admin_summary'),today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'});let selection={mode:'week',today,from:today,to:today,person:'all'};const draw=()=>{const box=document.querySelector('#admin-report');box.innerHTML=renderAdminReport(data,selection);box.querySelector('#admin-mode').onchange=e=>{selection.mode=e.target.value;draw()};box.querySelector('#admin-person').onchange=e=>{selection.person=e.target.value;draw()};for(const [id,key] of [['#admin-from','from'],['#admin-to','to']]){const field=box.querySelector(id);if(field)field.onchange=e=>{selection[key]=e.target.value;draw()}}};draw()}catch(x){error=x.message;render()}};document.querySelector('#create').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await auth.invoke('admin_create_user',{name:f.get('name'),email:f.get('email'),password:f.get('password')});error='帳號已建立，請安全地將臨時密碼提供給該成員。';render()}catch(x){error=x.message;render()}}}}
function training(){shell(`<h1>與 ${esc(session.character)} 面談</h1><p class="muted">LV${session.level} · 今日第 ${sessions.filter(s=>s.local_date===session.date).length+1} 場</p>${session.level===1?`<div class="card"><details><summary>簡化訪綱</summary><ol>${NODES.map(n=>`<li>${esc(n.replace('｜標準話稿',''))}</li>`).join('')}</ol></details></div>`:''}<div class="chat" id="chat">${session.turns.map(t=>`<div class="bubble ${t.role==='learner'?'me':''}">${esc(t.text)}</div>`).join('')||'<div class="bubble">你好，我們可以聊聊。</div>'}</div><div class="compose"><input id="utter" aria-label="面談內容" placeholder="說話或輸入測試內容"><button class="secondary" id="mic" ${speech.supported?'':'disabled'}>🎙 說話</button><button class="primary" id="send" ${busy?'disabled':''}>送出</button></div><p><small>${speech.supported?'即時語音辨識由瀏覽器提供；請在實機測試。':'此裝置不支援瀏覽器語音辨識，文字僅供測試。'}</small></p><button class="danger" id="end">結束面談</button>`);
 const input=document.querySelector('#utter');const send=async()=>{const text=input.value.trim();if(!text||busy)return;busy=true;try{const r=await auth.invoke('turn',{sessionId:session.id,text});session=r.session;error='';speech.speak(r.text);render();document.querySelector('#chat').scrollTop=1e8}catch(x){error=x.message;busy=false;render()}busy=false};document.querySelector('#send').onclick=send;input.onkeydown=e=>{if(e.key==='Enter')send()};document.querySelector('#mic').onclick=()=>{try{speech.listen({onText:t=>{input.value=t;send()},onError:e=>{error=`語音辨識：${e}`;render()},onEnd:()=>{}})}catch(x){error=x.message;render()}};document.querySelector('#end').onclick=async()=>{if(!confirm('確定結束面談？這場紀錄將保留。'))return;try{await auth.invoke('end',{sessionId:session.id,confirm:true});session=null;await refresh();error='本場已同步，評分需要複核；目前不計正式 PASS。';render()}catch(x){error=x.message;render()}}}
if(auth.refreshToken){refresh().then(render).catch(()=>{auth.clear();render()})}else render();
