import {CloudAuth} from '../auth/supabase-rest.js';
import {CLOUD_URL,CLOUD_KEY} from '../auth/config.js';
import {BrowserSpeechAdapter} from '../speech-adapter/browser.js';
import {NODES} from '../core/rules.js';
import {renderAdminReport} from './admin-report.js';
import {learnerAbility,characterGallery,materialsPage} from './learner-report.js';
import {historyPage,sessionDetailPage,statusLabel} from './session-view.js';
const auth=new CloudAuth(CLOUD_URL,CLOUD_KEY),speech=new BrowserSpeechAdapter(),root=document.querySelector('#app');
let profile=null,sessions=[],session=null,busy=false,error='',view='home',materials=null,reminderTimer=null,detail=null,selectedSessionId=null,pendingOnly=false,voiceStatus='尚未測試',voiceTranscript='',sessionBack='history',adminData=null,adminSelection=null,utteranceDraft='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(content){root.innerHTML=`<header><div class="bar"><div class="brand">TP927 <span class="version">V1.0 · Cloud Test</span></div><div class="row">${profile?`<small>${esc(profile.display_name)} · LV${profile.level}</small><button class="secondary" id="logout">登出</button>`:''}</div></div></header><main>${error?`<div class="notice">${esc(error)}</div>`:''}${content}</main>`;const out=document.querySelector('#logout');if(out)out.onclick=async()=>{try{await auth.signOut();error=''}catch{error='此裝置已登出；雲端登出未確認。'}finally{session=null;speech.stop();profile=null;sessions=[];materials=null;detail=null;view='home';render()}}}
function render(){clearTimeout(reminderTimer);reminderTimer=null;if(!profile)return login();if(view==='training'&&session)return training();if(view==='training')view='home';if(view!=='home')return learnerView();return dashboard()}
function login(){shell(`<h1>927 招募教練</h1><div class="card"><h2>管理者建立的帳號登入</h2><form id="login"><p><input type="email" name="email" required placeholder="電子郵件" autocomplete="username"></p><p><input type="password" name="password" required placeholder="密碼" autocomplete="current-password"></p><button class="primary">登入</button></form><p class="muted">V1 不開放自行註冊。帳號由管理者建立。</p></div><a href="./bootstrap.html">首次啟用管理者</a>`);document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await auth.signIn(f.get('email'),f.get('password'));await refresh();error='';render()}catch(x){error=x.message;render()}}}
async function refresh(){const data=await auth.invoke('history');profile=data.profile;sessions=data.sessions;session=data.activeSession||null}
async function recoverEndedSession(message='這場面談已結束，已返回首頁。'){
 await refresh();if(!session)utteranceDraft='';error=session?'面談仍在進行，您可以從首頁繼續。':message;view='home';render();return !session;
}
function dashboard(){const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'}),count=sessions.filter(s=>s.local_date===today).length;
 shell(`<h1>你好，${esc(profile.display_name)}</h1><div class="grid"><div class="card"><h3>目前等級</h3><div class="stat">LV${profile.level}</div></div><div class="card"><h3>今日訓練</h3><div class="stat">${count} / 3</div></div><div class="card"><h3>待複核</h3><div class="stat">${sessions.filter(s=>s.status==='review_required').length}</div><button class="secondary" id="pending">查看待複核紀錄</button></div></div><div class="card"><h2>${session?'進行中的面談':'開始今日訓練'}</h2><p>${session?`與 ${esc(session.character)} 的面談仍在進行，時間持續計算。返回首頁不會暫停或新增場次。`:'人物由系統抽取；每日最多三場。對話與驗證事件同步到專用雲端專案。'}</p><button class="primary" id="start" ${!session&&count>=3?'disabled':''}>${session?'繼續面談':'開始面談'}</button></div><div class="card"><h2>學習與紀錄</h2><div class="row"><button class="secondary" data-view="history">所有訓練紀錄</button><button class="secondary" data-view="voice">語音設備測試</button><button class="secondary" data-view="ability">我的能力</button><button class="secondary" data-view="characters">人物圖鑑</button><button class="secondary" data-view="materials">正式教材</button></div></div><div class="card"><h2>訓練紀錄</h2>${sessions.length?sessions.slice(0,5).map(s=>`<button class="session-row" type="button" data-session="${esc(s.id)}"><span>${esc(s.local_date)} · ${esc(s.character_name)} · LV${esc(s.level)}</span><span class="pill">${esc(statusLabel(s.status))}</span><span>查看紀錄 ›</span></button>`).join(''):'尚無紀錄。'}</div>${profile.is_admin?`<div class="card"><h2>管理者</h2><button class="secondary" id="summary">單位總覽</button><details><summary>建立初始帳號</summary><form id="create"><p><select name="name">${['江建廷','林宜慶','陳嘉瑋','顏伯存','劉孟凱'].map(x=>`<option>${x}</option>`).join('')}</select></p><p><input name="email" type="email" placeholder="成員電子郵件" required></p><p><input name="password" type="password" placeholder="臨時密碼，至少 12 字元" minlength="12" required></p><button class="primary">建立</button></form></details><div id="admin-report"></div></div>`:''}`);
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{pendingOnly=false;view=b.dataset.view;render()});
 document.querySelector('#pending').onclick=()=>{pendingOnly=true;view='history';render()};
 document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>openSession(b.dataset.session));
 document.querySelector('#start').onclick=async()=>{if(session){view='training';error='';render();return}try{const r=await auth.invoke('start');session=r.session;utteranceDraft='';view='training';error='';render()}catch(x){error=x.message;render()}};
 if(profile.is_admin){document.querySelector('#summary').onclick=async()=>{try{adminData=await auth.invoke('admin_summary');const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'});adminSelection??={mode:'week',today,from:today,to:today,person:'all'};drawAdmin()}catch(x){error=x.message;render()}};document.querySelector('#create').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await auth.invoke('admin_create_user',{name:f.get('name'),email:f.get('email'),password:f.get('password')});adminData=null;error='帳號已建立，請安全地將臨時密碼提供給該成員。';render()}catch(x){error=x.message;render()}};if(adminData)drawAdmin()}}
function drawAdmin(){const box=document.querySelector('#admin-report');if(!box||!adminData||!adminSelection)return;box.innerHTML=renderAdminReport(adminData,adminSelection);box.querySelectorAll('[data-admin-session]').forEach(b=>b.onclick=()=>openSession(b.dataset.adminSession,true));box.querySelector('#admin-mode').onchange=e=>{adminSelection.mode=e.target.value;drawAdmin()};box.querySelector('#admin-person').onchange=e=>{adminSelection.person=e.target.value;drawAdmin()};for(const [id,key] of [['#admin-from','from'],['#admin-to','to']]){const field=box.querySelector(id);if(field)field.onchange=e=>{adminSelection[key]=e.target.value;drawAdmin()}}}
function learnerView(){
 const body=view==='ability'?learnerAbility(sessions):view==='characters'?characterGallery(sessions):view==='history'?historyPage(sessions,{pendingOnly}):view==='session'?(detail?sessionDetailPage(detail):'<h1>單場紀錄</h1><p>正在載入…</p>'):view==='voice'?`<h1>語音設備測試</h1><div class="card"><p>此測試不建立訓練場次，也不保存錄音或測試文字。</p><p>語音辨識：${speech.supported?'瀏覽器提供':'此瀏覽器未提供'} · 語音播放：${speech.ttsSupported?'瀏覽器提供':'此瀏覽器未提供'}</p><div class="row"><button class="primary" id="voice-mic" ${speech.supported?'':'disabled'}>${speech.recognition?'停止收音':'開始測試收音'}</button><button class="secondary" id="voice-play" ${speech.ttsSupported?'':'disabled'}>測試角色語音</button></div><p id="voice-status" role="status">${esc(voiceStatus)}</p><p>辨識文字：<strong id="voice-text">${esc(voiceTranscript||'尚無')}</strong></p><small>請在 Safari 開啟網站並允許麥克風。若顯示不支援或權限遭拒，文字輸入仍可測試流程。</small></div>`:materials?materialsPage(materials):'<h1>927 正式教材</h1><p>正在載入…</p>';
 shell(`<button class="secondary" id="home">${view==='session'&&sessionBack==='history'?'返回紀錄':'返回首頁'}</button>${body}`);document.querySelector('#home').onclick=()=>{if(view==='voice')speech.stop();view=view==='session'?sessionBack:'home';detail=null;render()};
 if(view==='history')document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>openSession(b.dataset.session));
 if(view==='voice')wireVoiceCheck();
 if(view==='materials'&&!materials)auth.invoke('materials').then(r=>{materials=r.scripts;if(view==='materials')render()}).catch(x=>{error=x.message;view='home';render()});
}
async function openSession(id,admin=false){selectedSessionId=id;sessionBack=admin?'home':'history';detail=null;view='session';render();try{const r=await auth.invoke(admin?'admin_session_detail':'session_detail',{sessionId:id});if(selectedSessionId===id&&view==='session'){detail=r.session;error='';render()}}catch(x){error=x.message;view=sessionBack;render()}}
function voiceError(code){return ({'not-allowed':'麥克風權限遭拒。請在 Safari 網站設定允許麥克風。','audio-capture':'找不到可用麥克風。','no-speech':'未聽到語音，請靠近麥克風再試。','network':'語音辨識服務連線失敗。'}[code]||`語音辨識失敗：${code}`)}
function wireVoiceCheck(){
 const mic=document.querySelector('#voice-mic'),status=document.querySelector('#voice-status'),output=document.querySelector('#voice-text');
 const update=()=>{if(view!=='voice')return;status.textContent=voiceStatus;output.textContent=voiceTranscript||'尚無';mic.textContent=speech.recognition?'停止收音':'開始測試收音'};
 mic.onclick=()=>{if(speech.recognition){speech.stop();voiceStatus='正在停止收音…';update();return}voiceStatus='正在請求麥克風…';voiceTranscript='';update();try{speech.listen({onStart:()=>{voiceStatus='正在收音，請說一句話。';update()},onPartial:t=>{voiceTranscript=t;voiceStatus='正在辨識；測試文字不會送出或儲存。';update()},onText:t=>{voiceTranscript=t;voiceStatus='辨識完成，麥克風可用。';update()},onError:e=>{voiceStatus=voiceError(e);update()},onEnd:()=>{if(voiceStatus.startsWith('正在'))voiceStatus='收音已結束，沒有辨識到文字。';update()}});update()}catch(x){voiceStatus=x.message;update()}};
 document.querySelector('#voice-play').onclick=()=>{voiceStatus=speech.speak('你好，我們可以聊聊。')?'已要求播放測試語音。':'語音播放不可用，請確認裝置音量或瀏覽器設定。';update()};
}
 function training(){const lastCharacter=[...session.turns].reverse().find(t=>t.role==='character')?.text;const dayRows=sessions.filter(s=>s.local_date===session.date),ordinal=dayRows.length+(dayRows.some(s=>s.id===session.id)?0:1),remaining=40*60*1000-(Date.now()-Date.parse(session.startedAt));if(remaining>0)reminderTimer=setTimeout(()=>{if(session)render()},remaining);shell(`<button class="secondary" id="return-home">返回首頁</button><h1>與 ${esc(session.character)} 面談</h1><p class="muted">LV${session.level} · 今日第 ${ordinal} 場</p>${remaining<=0?'<div class="notice">已達 40 分鐘標準時間。可繼續面談，不會因此直接扣分或結束。</div>':''}${session.level===1?`<div class="card"><details><summary>簡化訪綱</summary><ol>${NODES.map(n=>`<li>${esc(n.replace('｜標準話稿',''))}</li>`).join('')}</ol></details></div>`:''}<div class="chat" id="chat">${session.turns.map(t=>`<div class="bubble ${t.role==='learner'?'me':''}">${esc(t.text)}</div>`).join('')||'<div class="bubble">你好，我們可以聊聊。</div>'}</div>${lastCharacter?`<p><button class="secondary" id="replay">播放上一句角色語音</button></p>`:''}<div class="compose"><input id="utter" aria-label="面談內容" value="${esc(utteranceDraft)}" placeholder="說話或輸入測試內容"><button class="secondary" id="mic" ${speech.supported?'':'disabled'}>🎙 說話</button><button class="primary" id="send" ${busy?'disabled':''}>送出</button></div><p id="mic-state" role="status"><small>${speech.supported?'按「說話」後會請求麥克風，辨識文字並送出；不保存完整錄音。':'此瀏覽器不支援語音辨識，請用 Safari 開啟或改用文字測試。'}</small></p><button class="danger" id="end">結束面談</button>`);
 const input=document.querySelector('#utter');input.oninput=()=>{utteranceDraft=input.value};let ending=false,submitted=false;const currentSessionId=session.id;
 const complete=async()=>{ending=true;speech.stop();try{await auth.invoke('end',{sessionId:currentSessionId,confirm:true});session=null;utteranceDraft='';await refresh();error='本場已同步，評分需要複核；目前不計正式 PASS。';view='home';render()}catch(x){if(x.message==='場次已結束'&&await recoverEndedSession())return;ending=false;error=x.message;render()}};
 const send=async()=>{const text=input.value.trim();if(!session||session.id!==currentSessionId||ending||submitted||!text||busy)return;submitted=true;utteranceDraft=text;speech.stop();busy=true;try{const r=await auth.invoke('turn',{sessionId:session.id,text});session=r.session;utteranceDraft='';error='';speech.speak(r.text);render();document.querySelector('#chat').scrollTop=1e8}catch(x){if(x.message==='場次已結束'&&await recoverEndedSession()){busy=false;return}error=x.message;busy=false;render()}busy=false};document.querySelector('#send').onclick=send;input.onkeydown=e=>{if(e.key==='Enter')send()};const mic=document.querySelector('#mic'),micState=document.querySelector('#mic-state');mic.onclick=()=>{if(speech.recognition){speech.stop();micState.textContent='正在停止收音…';return}micState.textContent='正在請求麥克風…';try{speech.listen({onStart:()=>{if(mic.isConnected){mic.textContent='停止收音';micState.textContent='正在收音，請說話。'}},onPartial:t=>{if(input.isConnected&&!submitted){input.value=t;utteranceDraft=t;micState.textContent='已辨識部分文字；可按「送出」。'}},onText:t=>{if(ending||submitted||!input.isConnected||!session||session.id!==currentSessionId)return;input.value=t;utteranceDraft=t;speech.stop();micState.textContent='辨識完成，正在送出文字…';send()},onError:e=>{if(mic.isConnected){micState.textContent=voiceError(e);mic.textContent='🎙 說話'}},onEnd:()=>{if(mic.isConnected){mic.textContent='🎙 說話';if(micState.textContent==='正在停止收音…'||micState.textContent.startsWith('已辨識部分文字'))micState.textContent=input.value.trim()?'收音已結束。辨識文字已留在輸入框，請按「送出」。':'收音已結束，沒有辨識到文字。'}}});mic.textContent='停止收音'}catch(x){micState.textContent=x.message;mic.textContent='🎙 說話'}};if(lastCharacter)document.querySelector('#replay').onclick=()=>{if(!speech.speak(lastCharacter))micState.textContent='此瀏覽器無法播放角色語音。'};
 document.querySelector('#end').onclick=()=>{if(confirm('確定結束面談？這場紀錄將保留。'))complete()};
 document.querySelector('#return-home').onclick=async()=>{speech.stop();view='home';error='';render();try{await recoverEndedSession()}catch(x){error=`已返回首頁；同步場次失敗：${x.message}`;render()}};
}
if(auth.refreshToken){refresh().then(render).catch(()=>{auth.clear();render()})}else render();
